apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: trader-liberty-build
    creationTimestam: null
  displayName: Trader on Liberty - Build
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: trader-liberty-dev
    creationTimestam: null
  displayName: Trader on Liberty - Dev
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: trader-liberty-stage
    creationTimestam: null
  displayName: Trader on Liberty - Stage
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: trader-liberty-prod
    creationTimestam: null
  displayName: Trader on Liberty - Prod
