apiVersion: v1
kind: Template
labels:
  template: trader-liberty-deploy
metadata:
  name: trader-liberty-deploy
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 9080-tcp
      port: 9080
      targetPort: 9080
      protoco: TCP
    - name: 9443-tcp
      port: 9443
      targetPort: 9443
      protoco: TCP
    - name: http
      port: 9082
      targetPort: 9082
      protoco: TCP
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Route
  id: ${APPLICATION_NAME}-http
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    to:
      name: ${APPLICATION_NAME}
    port:
      targetPort: 9443-tcp
    tls:
      termination: passthrough
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: JWT_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: jwt 
                key: audience
          - name: JWT_ISSUER
            valueFrom:
              secretKeyRef:
                name: jwt
                key: issuer
          - name: OIDC_NAME
            valueFrom:
              secretKeyRef:
                name: oidc
                key: name
                optional: true
          - name: OIDC_ISSUER
            valueFrom:
              secretKeyRef:
                name: oidc
                key: issuer
                optional: true
          - name: OIDC_AUTH
            valueFrom:
              secretKeyRef:
                name: oidc
                key: auth
                optional: true
          - name: OIDC_TOKEN
            valueFrom:
              secretKeyRef:
                name: oidc
                key: token
                optional: true
          - name: OIDC_ID
            valueFrom:
              secretKeyRef:
                name: oidc
                key: id
                optional: true
          - name: OIDC_SECRET
            valueFrom:
              secretKeyRef:
                name: oidc
                key: secret
                optional: true
          - name: OIDC_KEY
            valueFrom:
              secretKeyRef:
                name: oidc
                key: key
                optional: true
          - name: OIDC_NODEPORT
            valueFrom:
              secretKeyRef:
                name: oidc
                key: nodeport
                optional: true
          - name: PORTFOLIO_URL
            valueFrom:
              configMapKeyRef:
                name: urls
                key: portfolio
                optional: true
          - name: COM_IBM_HYBRID_CLOUD_SAMPLE_STOCKTRADER_TRADER_CLIENT_PORTFOLIOCLIENT_MP_REST_URL
            valueFrom:
              configMapKeyRef:
                name: urls
                key: portfolio
                optional: true
          - name: WLP_LOGGING_CONSOLE_FORMAT
            value: json
          - name: WLP_LOGGING_CONSOLE_SOURCE
            value: message,ffdc
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 9080
            name: 9080-tcp
            protocol: TCP
          - containerPort: 9443
            name: 9443-tcp
            protocol: TCP
          - containerPort: 9082
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9080
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
        terminationGracePeriodSeconds: 60
        dnsPolicy: ClusterFirst
        serviceAccountName: websphere
        serviceAccount: websphere
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStream
          name: ${APPLICATION_NAME}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: trader-liberty
